### ISSUE TITLE
Signed APK

### ISSUE THREAD

**Issue by IzzySoft** [flyteee-collections/dogeland#7]
Looks like you're no longer providing signed APK files at `releases/`. Could you please do so again?

**Comment by Flytreels** [comment]
yes will be later

**Comment by Flytreels** [comment]
Or you can sign and install by yourself

**Comment by IzzySoft** [comment]
> yes will be later

Thanks! Please give me a ping when it's available then.

> Or you can sign and install by yourself

The average user can't, sorry.

**Comment by Flytreels** [comment]
@IzzySoft **Thank you for waiting,** I finally added my own signature today, and it has brought a lot of experience improvement

**Comment by Flytreels** [comment]
but I am solving the problem of multi-language support, please be patient and wait for the new version to be launched

**Comment by IzzySoft** [comment]
Ah – I just was about to ask where to find that signed APK :rofl: OK, waiting for your next ping then.

And glad to read it wasn't "just a burden", but brought some useful experience along :smiley:
